### ISSUE TITLE
Improve path & point storage

### ISSUE THREAD

**Issue by tavaughan** [SlicerIGT/SlicerPathReconstruction#2]
If we do not detect and handle this, then the number of points and the number of paths could become different, and the association will become lost.

**Comment by lassoan** [comment]
How do you associate them now? Use two role names and role indexes? That is not robust. 

Instead, you can do what is done in Sequence browser module: generate unique role name prefixes. These prefixes are stored in the node as a string list.

**Comment by tavaughan** [comment]
Thanks Andras for the comment. You are referring to something like this? https://github.com/SlicerRt/Sequences/blob/master/SequenceBrowser/MRML/vtkMRMLSequenceBrowserNode.cxx#L804

I was thinking maybe I could create a new node class for storing the association. Something like vtkMRMLPathNode (which would reference the points model node, path model node, maybe support for other reference roles for accuracy assessment, etc). Do you think this has any disadvantages compared to the other approach?

**Comment by lassoan** [comment]
> You are referring to something like this? https://github.com/SlicerRt/Sequences/blob/master/SequenceBrowser/MRML/vtkMRMLSequenceBrowserNode.cxx#L804

Yes.

> I was thinking maybe I could create a new node class for storing the association.

Such small internal details should be not exposed to the scene and other modules. It would generate more nodes that needs to be kept in sync with the path reconstruction nodes. It would be very difficult to make the behavior correct, when deleting the path reconstruction node, using path reconstruction node as a singleton node (in that case adding a new node overwrites the old node; and we would need to delete the old orphan additional nodes), or when making time sequence of path reconstruction nodes (we would need to add proxy nodes for all additional nodes). The module logic would need to observe a scene and try to detect what's happening and fix any inconsistencies and remove orphan nodes - which would be complex and error-prone.

Generating node prefixes in the node might make the node slightly more complex, but would greatly simplify the overall design.
